// <auto-generated />
namespace DongHoShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RevenuseStatisticSP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevenuseStatisticSP));
        
        string IMigrationMetadata.Id
        {
            get { return "202203150735162_RevenuseStatisticSP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
